
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Relative to prisma/schema.prisma — resolves to prisma/dev.db
    // Runtime (Next.js) uses DATABASE_URL=file:./prisma/dev.db from .env
    url: "file:./dev.db",
  },
});
